config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: %i[show new create index]
  devise_for :users, :controllers => { registrations: 'registrations'}
  # Two factor add
  devise_scope :user do
    scope :users, as: :users do
      post 'pre_otp', to: 'registrations#pre_otp'
    end
  end

  resource :two_factor

  # end

  resources :articles, only: %i[new create destroy show index edit] do 
    resources :votes, only: %i[create destroy]
  end
  
  root 'categories#index'
end

app/models/article.rb
class Article < ApplicationRecord
  include ImageUploader::Attachment(:image)
  belongs_to :author, class_name: 'User'
  has_many :votes, dependent: :destroy
  has_and_belongs_to_many :categories
  has_rich_text :body

  validates :title, presence: true
  validates :text, presence: true
  scope :most_popular, -> { find_by(votes_count: maximum(:votes_count)) }
  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
    @categories = Category.all
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        @article.categories << Category.find(category_ids)
        format.html { redirect_to root_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :text, :image)
  end

  def category_ids
    params[:selected_id]
  end
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :title, label: "What's the title of your article?", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "Incredible title here...", autofocus: true %><br />
      <%= f.input :text, label: "Fill the content of your article:", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "Awesome content article here..." %>
      <br>
      <%= f.input :image, label: "Select your image", input_html: { class: "file", value: @article.cached_image_data}, wrapper: false, label_html: {class: "label"} %>
      <br>
      <%= fields_for(@selected) do |s| %>
      <strong><%= s.label :categories %></strong><br><br>
      <%= s.collection_select(:selected_id, @categories, :id, :name, {selected: 2, include_hidden: false}, { multiple: true }) %>
    <% end %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-dark" %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<section class="hero is-large is-info">
  <div class="hero-body">
    <p class="title">
      Large hero
    </p>
    <p class="subtitle">
      Large subtitle
    </p>
  </div>
</section>
<section class="hero is-medium is-danger">
  <div class="hero-body">
    
    <p class="title">
      Medium hero
    </p>
    <p class="subtitle">
      Medium subtitle
    </p>
  </div>
</section>

app/views/articles/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered box">
			<div class="column is-three-fifths">
				<h1 class="title">Create a New Article</h1>
					<%= render 'form', article: @article %>
			</div>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<section class="hero is-large is-info">
  <div class="columns">
    <div class="column container">
      <div class="hero-body p-6 mx-6">
        <div class="card mx-6">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src='<%= display_photo(@article) %>' alt=".">
            </figure>
          </div>
          <div class="card-content">
            <p class="title">
              <%= @article.title %>
            </p>
            <div class="content">
              <%= @article.text %>
            </div>
          </div>  
      </div>
    </div>
    

  </div>  
</section>