config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: %i[show new create index]
  devise_for :users, :controllers => { registrations: 'registrations'}
  # Two factor add
  devise_scope :user do
    scope :users, as: :users do
      post 'pre_otp', to: 'registrations#pre_otp'
    end
  end

  resource :two_factor

  # end

  resources :articles, only: %i[new create destroy show index edit] do 
    resources :votes, only: %i[create destroy]
  end
  
  root 'categories#index'
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :articles
  validates :name, presence: true, length: { mininum: 2, maximum: 20 }

  scope :priority_order, -> { order(:priority) }

  def most_recent_article
    articles.most_recents.limit(1)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories or /categories.json
  def index
    @categories = Category.includes(:articles).all
    articles = Article.all
    @xcat = Category.all.order(:priority)
    @most_popular = articles.most_popular
    @articles_by_category = []
    @categories.each do |category|
      @articles_by_category << recent_article(category) unless recent_article(category).nil?
    end
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.includes(:articles).find(params[:id])
    recent_related_articles
  end

  private

  def recent_related_articles
    @recent_related_articles ||= @category.articles.ordered_by_most_recent.limit(4)
  end

  def recent_article(category)
    category.articles.ordered_by_most_recent.first
  end
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<section class="hero is-halfheight is-info" style="background: url(<%= show_popular %>) center center; background-size: cover">
  
  <div class="hero-body mb-5">
  </div>
  <div class="hero-foot mb-5">
    <div class="ml-5 mb-3">
      <p class="title is-size-3">
        <%= @most_popular.title %>
      </p>
      <p class="subtitle is-size-5">
        <%= @most_popular.text.to_s.truncate_words(60) %>
      </p>
    </div>
  </div>
</section>
<section class="hero is-medium is-info">
    <%= show_articles_by_categories(@articles_by_category) %>  
</section>

  

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="cont grid">
  <% @recent_related_articles.each_with_index do |art, ind| %>
    <div class="grid">
      <%= four_articles(art, ind)%>
    </div>
  <% end %>
</div>